- hosts: all
  become: yes
  tasks:
    - name: Installing Apache
      yum:
        name: httpd
        state: latest
    - name: Start Apache
      service:
        name: httpd
        enabled: yes
        state: started